### ISSUE TITLE
フォントを変更する

### ISSUE THREAD

**Issue by void2610** [nitfc-festival-system-team/2023hp#77]

**Comment by kakenore** [comment]
![image](https://github.com/nitfc-festival-system-team/2023hp/assets/52400027/d949b1d3-6df2-4341-9720-6825c22d859c)
ラノベPOPV2使った感じです

テーマが再生を意味しているらしいので再生→生まれ変わり→転生→なろう系→ラノベということでラノベPOPV2をお知らせとかイベント告知のためのフォントに推したいです。

**Comment by kakenore** [comment]
![image](https://github.com/nitfc-festival-system-team/2023hp/assets/52400027/4f949624-face-4b10-9f5a-006608134711)
ラノベPOPV2を実装した図

テーマが「REBOOOOON」らしく、再生を意味するらしいので
再生→生まれ変わり→転生→なろう系→ラノベということでこれを推します
